import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "@/components/header";
import { Main } from "@/components/main";
import { Skills } from "@/components/skills";
import { About } from "@/components/about-me";
import { Projects } from "@/components/projects";
import { Contacts } from "@/components/contacts";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ali Elsheikh</title>
        <meta name="description" content="Ali Elsheikh portfolio, Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          property="og:image"
          content="/images/open-graph.png"
        />
        <meta property="og:image:type" content="image/png" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Skills />
      <About />
      <Projects />
      <Contacts />
      <Footer />
    </>
  );
}
